jpa:
  properties:
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
spring:
  profiles: test
app :
  yml :
      string : t_stringTest_applicationYML
      boolean :
          false : false
          true : true
      map :
          property-name: '{
            key1: "value1_test",
            key2: "value2_test"
          }'
---
spring:
  profiles: prod
app :
  yml :
      string : p_stringTest_applicationYML
      boolean :
          false : false
          true : true
      map:
          property-name: '{
             key1: "value1_prod",
             key2: "value2_prod"
           }'